### ISSUE TITLE
Category is not active in the list when it's being viewed

### ISSUE THREAD

**Issue by jcaudle** [aetrion/dnsimple-support#102]
We should assign the `active` class to the Category on the side bar when it is being viewed.

![screen shot 2015-10-08 at 10 42 04 am](https://cloud.githubusercontent.com/assets/301553/10369659/6663b91a-6da9-11e5-8b56-5a018734550b.png)

**Comment by weppos** [comment]
:+1: however...

Welcome to hell :smiling_imp:  I believe I spent one day trying to make it working and I then decided to move on. :grin:

**Comment by jcaudle** [comment]
Yeah, I wanted to note it. I took a brief look into it and am already going to move on for now. :wink:

**Comment by sbastn** [comment]
I spend 30m on this and gave up.

**Comment by jacegu** [comment]
This issue is starting to sound like a challenge...

**Comment by jcaudle** [comment]
Have at it @jacegu.
