### ISSUE TITLE
Inconsistent font-size for steps

### ISSUE THREAD

**Issue by meeunier** [aetrion/dnsimple-support#111]
ex.: http://support.dnsimple.com/articles/account-activation/

`class="section-steps"` should have same font size as `<p>`

**Comment by weppos** [comment]
@meeunier FYI I decreased it on purpose (I believe it was 90%) to make it more compact and different than the body of the page. That said, I'll leave the final word to @sbastn

**Comment by sbastn** [comment]
Could we do something like this?
<img width="765" alt="screen shot 2015-10-08 at 9 12 03 pm" src="https://cloud.githubusercontent.com/assets/80610/10377027/4c58f834-6e01-11e5-88fe-9d00b692f161.png">
