### ISSUE TITLE
Email category duplicated?

### ISSUE THREAD

**Issue by sbastn** [aetrion/dnsimple-support#126]
<img width="272" alt="screen shot 2015-11-19 at 11 25 16 am" src="https://cloud.githubusercontent.com/assets/80610/11268283/603be74c-8eb0-11e5-8725-521073419fcf.png">
<img width="241" alt="screen shot 2015-11-19 at 11 26 39 am" src="https://cloud.githubusercontent.com/assets/80610/11268297/6a816f92-8eb0-11e5-99ea-927770c91a08.png">
<img width="482" alt="screen shot 2015-11-19 at 11 26 50 am" src="https://cloud.githubusercontent.com/assets/80610/11268300/709f1fb4-8eb0-11e5-8f28-4354deff533e.png">

**Comment by aeden** [comment]
Pluralization FTW! Should we fix the categories in the offending articles, or improve the category display logic (which seems to be a more daunting task)?

**Comment by weppos** [comment]
I'd fix email -> emails. That was clearly a mistake/typo when the article was created.

**Comment by sbastn** [comment]
Fixed by #129
