### ISSUE TITLE
Create new account feature support articles

### ISSUE THREAD

**Issue by aeden** [aetrion/dnsimple-support#61]
These are the new articles that we need to add:

- [x] Setting up a team
- [x] Switching accounts
- [x] Adding and removing team members

**Comment by aeden** [comment]
@weppos will create a checklist of new articles needed

**Comment by jacegu** [comment]
@weppos I have added the articles I see missing from the top of my head. Please take a quick look whenever you have a couple minutes and add anything that's missing.

**Comment by weppos** [comment]
I think for now we can start with a single article called "Accounts" where we add information about what we mean with account and standard procedures such as:

- Creating an account
- Deleting an account
- Adding/Removing a member
- Switching account

We can also have a companion multi-user account, linked from that one, that represents a sort of deeper overview about the connection between users and accounts.

**Comment by jcaudle** [comment]
All requested articles have been added to #67

**Comment by jcaudle** [comment]
I will note that deleting an account is not supported right now.
