### ISSUE TITLE
Update yearly billing article

### ISSUE THREAD

**Issue by jacegu** [aetrion/dnsimple-support#64]
http://support.dnsimple.com/articles/yearly-billing/

**Comment by aeden** [comment]
Depends on https://github.com/aetrion/dnsimple/pull/2168

**Comment by jacegu** [comment]
This could simply say that switching your billing period is just changing to a monthly/yearly plan and point to the change plan article (that doesn't exist yet). We can use this as an opportunity to create it with updated screenshots reflecting the new plans.
