### ISSUE TITLE
Categories should be sorted alphabetically

### ISSUE THREAD

**Issue by sbastn** [aetrion/dnsimple-support#85]
This is hard to scan since there is no order to it:

<img width="280" alt="screen shot 2015-10-08 at 8 32 11 am" src="https://cloud.githubusercontent.com/assets/80610/10359246/18b0b310-6d97-11e5-8a52-160f87b9520a.png">

**Comment by weppos** [comment]
They were not sorted automatically on purpose: they are ordered based on potential similarities and importance.

For example, if you sort them alphabetically then the general DNSimple category will slip to the middle. Advanced DNS will jump at the top and, more importantly, it will be far from the DNS category (whereas it makes sense to keep them close).

The last 3 items, instead, are integrations.

I vote :-1: to sort them. They are just a few, therefore it's fairly easy to read them all.

**Comment by Barbamama** [comment]
Ok that makes sense... forget about alphabetical then. thank you @sbastn for the link to this issue

**Comment by sbastn** [comment]
If we could group them together, in a "category of categories", it might work. 

I don't know if that's feasible with the current publishing framework that we use, but we could have:

* Domains
  * Transfers
  * WHOIS privacy
  * Email
  * Services

* DNS
  * Basic DNS
  * Advanced DNS
  * Name servers

* FAQs (previously DNSimple, these could be better categorized)

* Integrations
  * API
  * Heroku
  * GitHub

* SSL Certificates

I think it's a bit better than what we have right now.

**Comment by weppos** [comment]
FYI the decision to not nest categories was a deliberate decision to keep it simple (nesting introduces a bunch of complications).

Can I ask how the current list of categories represents an issue? There is a search feature, and the number of categories is limited.

**Comment by aeden** [comment]
> Can I ask how the current list of categories represents an issue? There is a search feature, and the number of categories is limited.

There is an implicit grouping which makes sense to us, but for someone who has no concept of domains and DNS, the grouping may appear arbitrary and difficult to scan.

**Comment by weppos** [comment]
Wouldn't the search be sufficient to overcome possible difficulties to find articles?

**Comment by aeden** [comment]
> Wouldn't the search be sufficient to overcome possible difficulties to find articles?

Maybe, but you asked how it was an issue, and I told you.

**Comment by sbastn** [comment]
The current number of categories is 17. It's not a small number anymore.

**Comment by weppos** [comment]
> The current number of categories is 17. It's not a small number anymore.

Personally, I always said that at least the following categories did not make a big sense to me.

- Heroku and DNSimple
- Github and DNSimple
- CloudFlare and DNSimple
- Slack and DNSimple

It also always confused be DNS vs Advanced DNS (as the concept of advance is somehow subjective).

**Comment by sbastn** [comment]
Personally I find the categories hard to use. I don't find them useful. I always use the search.

I would consider removing the categories and make the search more prominent.

Underneath the search, I would have "soft" categories, "New to DNS", "Secure your domain", "FAQs about DNSimple's services" to guide people to the right content.

Mailchimp has a good example of this: http://kb.mailchimp.com/

And if we go that route, it could be the opportunity to move the support docs to `jekyll`
