### ISSUE TITLE
Provide an obvious link back to application

### ISSUE THREAD

**Issue by sbastn** [aetrion/dnsimple-support#89]
Add a clear link to the application. Currently on the footer, it's not easy to spot and hard to reach. Probably on the top nav bar?

**Comment by weppos** [comment]
The logo on both developer/support sites is the DNSimple logo, which is also misleading. One proposal can be to find an icon to place on the right of the current logo, and change the logo to be something more close to the site itself (such as DNSimple Help or similar).

**Comment by aeden** [comment]
:+1: on changing the logo on the support site to include the word Help or Support. I think that with that plus a text link "Go to DNSimple.com" would be sufficient.
