### ISSUE TITLE
Link at bottom of SSL Certificate with Heroku page is no longer valid

### ISSUE THREAD

**Issue by aeden** [aetrion/dnsimple-support#97]
The last link out on the following page points to a location that no longer exists:

http://support.dnsimple.com/articles/ssl-certificate-with-heroku/

**Comment by aeden** [comment]
I wonder, do we want to continue linking out to other sites?

**Comment by weppos** [comment]
I agree that we may want to delete that section now that we have the wizard and the other articles. At some point, we may want to write support articles that explains the wizard and/or the options.

**Comment by sbastn** [comment]
Closing as we no longer link to external sites on that page.
